-- MySQL Script generated by MySQL Workbench
-- Wed Dec 21 10:46:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cooking-app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cooking-app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cooking-app` DEFAULT CHARACTER SET utf8 ;
USE `cooking-app` ;

-- -----------------------------------------------------
-- Table `cooking-app`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cooking-app`.`users` ;

CREATE TABLE IF NOT EXISTS `cooking-app`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `favorite_id` INT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cooking-app`.`dishes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cooking-app`.`dishes` ;

CREATE TABLE IF NOT EXISTS `cooking-app`.`dishes` (
  `dish_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` SET('starter', 'main course', 'dessert') NOT NULL,
  PRIMARY KEY (`dish_id`),
  UNIQUE INDEX `recipe_id_UNIQUE` (`dish_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cooking-app`.`recipes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cooking-app`.`recipes` ;

CREATE TABLE IF NOT EXISTS `cooking-app`.`recipes` (
  `recipe_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `dish_id` INT NULL,
  PRIMARY KEY (`recipe_id`),
  UNIQUE INDEX `recipe_id_UNIQUE` (`recipe_id` ASC) VISIBLE,
  INDEX `recipes_dish_id_idx` (`dish_id` ASC) VISIBLE,
  CONSTRAINT `recipes_dish_id`
    FOREIGN KEY (`dish_id`)
    REFERENCES `cooking-app`.`dishes` (`dish_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cooking-app`.`ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cooking-app`.`ingredients` ;

CREATE TABLE IF NOT EXISTS `cooking-app`.`ingredients` (
  `ingredient_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ingredient_id`),
  UNIQUE INDEX `ingredient_id_UNIQUE` (`ingredient_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cooking-app`.`step`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cooking-app`.`step` ;

CREATE TABLE IF NOT EXISTS `cooking-app`.`step` (
  `recipe_id` INT NOT NULL,
  `measurement_id` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`recipe_id`, `measurement_id`),
  INDEX `step_measurement_id_idx` (`measurement_id` ASC) VISIBLE,
  CONSTRAINT `step_recipe_id`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `cooking-app`.`recipes` (`recipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `step_measurement_id`
    FOREIGN KEY (`measurement_id`)
    REFERENCES `cooking-app`.`measurements` (`step_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cooking-app`.`measurements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cooking-app`.`measurements` ;

CREATE TABLE IF NOT EXISTS `cooking-app`.`measurements` (
  `step_id` INT NOT NULL,
  `ingredient_id` INT NOT NULL,
  `quantity` FLOAT NOT NULL,
  `step_id` INT NOT NULL,
  PRIMARY KEY (`step_id`, `ingredient_id`),
  UNIQUE INDEX `recipes_id_UNIQUE` (`step_id` ASC) VISIBLE,
  UNIQUE INDEX `ingredient_id_UNIQUE` (`ingredient_id` ASC) VISIBLE,
  CONSTRAINT `measurements_ingredient_id`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `cooking-app`.`ingredients` (`ingredient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `measurements_step_id`
    FOREIGN KEY (`step_id`)
    REFERENCES `cooking-app`.`step` (`recipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cooking-app`.`favorites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cooking-app`.`favorites` ;

CREATE TABLE IF NOT EXISTS `cooking-app`.`favorites` (
  `user_id` INT NOT NULL,
  `recipe_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `recipe_id`),
  INDEX `favorite_recipe_id_idx` (`recipe_id` ASC) VISIBLE,
  CONSTRAINT `favorite_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `cooking-app`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `favorite_recipe_id`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `cooking-app`.`recipes` (`recipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;