-- MySQL Script generated by MySQL Workbench
-- Wed Dec 21 15:45:40 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema music-app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema music-app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `music-app` DEFAULT CHARACTER SET utf8 ;
USE `music-app` ;

-- -----------------------------------------------------
-- Table `music-app`.`album`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `music-app`.`album` ;

CREATE TABLE IF NOT EXISTS `music-app`.`album` (
  `id_album` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `genre` VARCHAR(255) NOT NULL,
  `picture` VARCHAR(255) NOT NULL,
  `artist` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_album`),
  UNIQUE INDEX `id_album_UNIQUE` (`id_album` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music-app`.`track`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `music-app`.`track` ;

CREATE TABLE IF NOT EXISTS `music-app`.`track` (
  `id_track` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NOT NULL,
  `youtube_url` VARCHAR(255) NOT NULL,
  `id_album` INT NULL,
  PRIMARY KEY (`id_track`),
  UNIQUE INDEX `id_track_UNIQUE` (`id_track` ASC) VISIBLE,
  CONSTRAINT `track_id_album`
    FOREIGN KEY (`id_track`)
    REFERENCES `music-app`.`album` (`id_album`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
